# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath("../../"))


# -- Project information -----------------------------------------------------

project = "Qdislib"
copyright = "2025, Barcelona Supercomputing Center (BSC)"
html_show_copyright = False
author = "Barcelona Supercomputing Center (BSC)"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The full version, including alpha/beta/rc tags.
init_contents = open("../../Qdislib/__init__.py").readlines()
for line in init_contents:
    if "__version__" in line:
        clean_line = line.strip()
        version, value = clean_line.split("=")
        release = value.strip().replace('"', "").replace("'", "")

# The short X.Y version.
version = ".".join(release.split(".")[:-1])

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'


# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.viewcode",
    "sphinx.ext.napoleon",
    "sphinx.ext.intersphinx",
    # 'sphinx.ext.linkcode',  # take a look
    "sphinx.ext.autosummary",
    "nbsphinx",
    "nbsphinx_link",
    "sphinx_mdinclude",
    "sphinx_autodoc_typehints",
    "notfound.extension",
    "sphinxemoji.sphinxemoji",
    "versionwarning.extension",
]

nbsphinx_execute = "never"

napoleon_google_docstring = False
napoleon_use_param = False
napoleon_use_ivar = True

autodoc_mock_imports = ["pycompss"]
autodoc_preserve_defaults = True
autodoc_function_signature_with_arguments_on_newline = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ["Qdislib.classes.rst"]


# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = "index"

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# sphinx-notfound-page
notfound_context = {
    "title": "Page Not Found",
    "body": """
<h1>Page Not Found</h1>

<p>Sorry, we couldn't find that page.</p>

<p>Try using the search box or go to the homepage.</p>
""",
}

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_material"  # 'sphinx_rtd_theme'
# https://sphinx-themes.org/sample-sites/sphinx-material/

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

html_css_files = ["custom.css"]

html_logo = "../logo.png"
html_favicon = "../logo.png"

# Material theme options (see theme.conf for more information)
html_theme_options = {
    # Set the name of the project to appear in the navigation.
    "nav_title": "Qdislib",
    # Set you GA account ID to enable tracking
    # 'google_analytics_account': 'UA-XXXXX',
    # Specify a base_url used to generate sitemap.xml. If not
    # specified, then no sitemap will be built.
    "base_url": "https://qdislib.readthedocs.io",
    # Set the color and the accent color
    "color_primary": "purple",
    "color_accent": "light-blue",
    # Set the repo location to get a badge with stats
    "repo_url": "https://github.com/bsc-wdc/qdislib",
    "repo_name": "Qdislib",
    # Visible levels of the global TOC; -1 means unlimited
    "globaltoc_depth": 3,
    # If False, expand all TOC entries
    "globaltoc_collapse": False,
    # If True, show hidden TOC entries
    "globaltoc_includehidden": False,
    "html_minify": True,
    "css_minify": True,
    # 'logo_icon': '&#xe869',
}

# -- Options for LaTeX output ---------------------------------------------

latex_engine = "xelatex"
latex_additional_files = ["./_static/bsc_logo.jpg"]
latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    "papersize": "a4paper",
    "releasename": " ",
    # Sonny, Lenny, Glenn, Conny, Rejne, Bjarne and Bjornstrup
    # 'fncychap': '\\usepackage[Lenny]{fncychap}',
    "fncychap": "\\usepackage{fncychap}",
    "fontpkg": "\\usepackage{amsmath,amsfonts,amssymb,amsthm}",
    "figure_align": "htbp",
    # The font size ('10pt', '11pt' or '12pt').
    #
    "pointsize": "10pt",
    # Additional stuff for the LaTeX preamble.
    #
    "preamble": r"""
        %%%%%%%%%%%%%%%%%%%% PREAMBLE %%%%%%%%%%%%%%%%%%
        %%% Add number to subsubsection 2=subsection, 3=subsubsection
        %%% Below subsubsection is not good idea.
        \setcounter{secnumdepth}{3}

        %%% Table of content upto 2=subsection, 3=subsubsection
        \setcounter{tocdepth}{2}

        %%% Load packages
        \usepackage{amsmath,amsfonts,amssymb,amsthm}
        \usepackage{graphicx}
        % \usepackage[strings]{underscore}
        % \usepackage[T1]{fontenc}
        % \usepackage{lmodern}
        % \usepackage[utf8]{inputenc}

        %%% Reduce spaces for Table of contents, figures and tables-
        %%% It is used "\addtocontents{toc}{\vskip -1.2cm}" etc. in the document
        \usepackage[notlot,nottoc,notlof]{}

        \usepackage{color}
        \usepackage{transparent}
        \usepackage{eso-pic}
        \usepackage{lipsum}

        %%% Link at the footnote to go to the place of footnote in the text
        \usepackage{footnotebackref}
        \makeatletter
        \LetLtxMacro{\BHFN@Old@footnotemark}{\@footnotemark}

        \renewcommand*{\@footnotemark}{%
            \refstepcounter{BackrefHyperFootnoteCounter}%
            \xdef\BackrefFootnoteTag{bhfn:\theBackrefHyperFootnoteCounter}%
            \label{\BackrefFootnoteTag}%
            \BHFN@Old@footnotemark
        }
        \makeatother

        %%% Spacing between line
        \usepackage{setspace}
        %%%% \onehalfspacing
        %%%% \doublespacing
        \singlespacing

        %%% Datetime
        \usepackage{datetime}
        \newdateformat{MonthYearFormat}{%
            \monthname[\THEMONTH], \THEYEAR}

        %% RO, LE will not work for 'oneside' layout.
        %% Change oneside to twoside in document class
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhf{}

        %%% Alternating Header for oneside
        \fancyhead[L]{\ifthenelse{\isodd{\value{page}}}{ \small \nouppercase{\leftmark} }{}}
        \fancyhead[R]{\ifthenelse{\isodd{\value{page}}}{}{ \small \nouppercase{\rightmark} }}

        %%% Alternating Header for two side
        %\fancyhead[RO]{\small \nouppercase{\rightmark}}
        %\fancyhead[LE]{\small \nouppercase{\leftmark}}

        %%% For oneside: change footer at right side. If you want to use Left and right then use same as header defined above.
        \fancyfoot[R]{\ifthenelse{\isodd{\value{page}}}{{\tiny BSC-WDC Group} }{\href{http://www.bsc.es}{\tiny BSC}}}

        %%% Alternating Footer for two side
        %\fancyfoot[RO, RE]{\scriptsize BSC-WDC Group (support-compss@bsc.es)}

        %%% page number
        \fancyfoot[CO, CE]{\thepage}

        \renewcommand{\headrulewidth}{0.5pt}
        \renewcommand{\footrulewidth}{0.5pt}

        \RequirePackage{tocbibind} %%% comment this to remove page number for following
        \addto\captionsenglish{\renewcommand{\contentsname}{Table of contents}}
        \addto\captionsenglish{\renewcommand{\listfigurename}{List of figures}}
        \addto\captionsenglish{\renewcommand{\listtablename}{List of tables}}
        % \addto\captionsenglish{\renewcommand{\chaptername}{Chapter}}

        %%% Reduce spacing for itemize
        \usepackage{enumitem}
        \setlist{nosep}

        %%% Quote Styles at the top of chapter
        \usepackage{epigraph}
        \setlength{\epigraphwidth}{0.8\columnwidth}
        \newcommand{\chapterquote}[2]{\epigraphhead[60]{\epigraph{\textit{#1}}{\textbf {\textit{--#2}}}}}
        %%% Quote for all places except Chapter
        \newcommand{\sectionquote}[2]{{\quote{\textit{``#1''}}{\textbf {\textit{--#2}}}}}

        %%%%%%%%%%%%%%%%%% END PREAMBLE %%%%%%%%%%%%%%%%%
    """,
    "maketitle": r"""
        \pagenumbering{Roman} %%% to avoid page 1 conflict with actual page 1

        \begin{titlepage}
            \centering

            \vspace*{40mm} %%% * is used to give space from top
            %%% \textbf{\Huge {Title over the logo}}

            \vspace{0mm}
            \begin{figure}[!h]
             \centering
             \includegraphics[scale=0.4]{logo.png}
            \end{figure}

            \vspace{0mm}
            \Huge \textbf{{Qdislib Manual}}

            \Large Workflows and Distributed Computing Group
            % \vspace{0mm}

            %% \vfill adds at the bottom
            \vfill

            \large  Last updated : \MonthYearFormat\today
            \vspace*{5mm}

            \normalsize \textit{Online version available at }{\href{https://qdislib.readthedocs.io/en/latest/}{Qdislib - ReadTheDocs}}
            \vspace*{20mm}

            \begin{figure}[!h]
             \centering
             \includegraphics[scale=0.3]{bsc_logo.jpg}
            \end{figure}
        \end{titlepage}

        \clearpage
        \pagenumbering{roman}
        \tableofcontents
        \listoffigures
        \listoftables
        \clearpage
        \pagenumbering{arabic}

        """,
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
    "sphinxsetup": "hmargin={0.7in,0.7in}, vmargin={1in,1in}, \
        verbatimwithframe=true, \
        TitleColor={rgb}{0,0,0}, \
        HeaderFamily=\\rmfamily\\bfseries, \
        InnerLinkColor={rgb}{0,0,1}, \
        OuterLinkColor={rgb}{0,0,1}",
    "tableofcontents": " ",
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (
        master_doc,
        "Qdislib.tex",
        "Qdislib Documentation",
        "Barcelona Supercomputing Center",
        "manual",
    ),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = "../logo.png"

# Disable xindy
latex_use_xindy = False

# If true, show page references after internal links.
latex_show_pagerefs = False

# If true, show URL addresses after external links.
latex_show_urls = "footnote"

# Documents to append as an appendix to all manuals.
latex_appendices = []

# If false, no module index is generated.
latex_domain_indices = True

# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, "Qdislib", "Qdislib Documentation", [author], 1)]


# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        "Qdislib",
        "Qdislib Documentation",
        author,
        "Qdislib",
        "Quantum Distributed Library.",
        "Miscellaneous",
    ),
]

# Documents to append as an appendix to all manuals.
texinfo_appendices = []

# If false, no module index is generated.
texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
texinfo_show_urls = "footnote"

# If true, do not generate a @detailmenu in the "Top" node's menu.
texinfo_no_detailmenu = False

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", (None, "python-inv.txt"))
}
